import type { Metadata } from "next";
import { Provider } from "staking-dashboard/components/ui/provider";
import Layouts from "staking-dashboard/containers/Layouts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Provider>
          <Layouts>{children}</Layouts>
        </Provider>
      </body>
    </html>
  );
}
