import type { Metadata } from "next";
import { Provider } from "staking-dashboard/components/ui/provider";
import AppKitProvider from "staking-dashboard/containers/AppKitProvider";
import Layouts from "staking-dashboard/containers/Layouts";
import { NetworkProvider } from "staking-dashboard/containers/NetworkProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <AppKitProvider>
          <Provider>
            <NetworkProvider>
              <Layouts>{children}</Layouts>
            </NetworkProvider>
          </Provider>
        </AppKitProvider>
      </body>
    </html>
  );
}
